### ISSUE TITLE
Implemented aggregation is different from the description in McMahan 2016 paper

### ISSUE THREAD

**Issue by bokun-wang** [vaseline555/Federated-Learning-in-PyTorch#10]
Hello. Thanks for the nice repo.

I have a question about the implementation of aggregation on the server. According to the McMahan 2016 paper, the server does
$$w_{t+1}\leftarrow \sum_{k\in S_t} \frac{n_k}{m_t} w_{t+1}^k.$$

If I understand it correctly, there is a server-side optimizer in your code and [your implementation](https://github.com/vaseline555/Federated-Learning-in-PyTorch/blob/7607857265a2ef4b71a67f892965cbf0f2d52aac/src/algorithm/fedavg.py#L33C1-L41C1) can be translated into

$$w_{t+1}\leftarrow w_t - \eta(w_t - \sum_{k\in S_t} \frac{n_k}{m_t} w_{t+1}^k).$$

This looks like a momentum update of the server's model. Could you please explain the motivation behind this?

**Comment by vaseline555** [comment]
Dear @bokun-wang,
Hi! Thank you for your interest in my repository. 😃 

Exactly as you understood, it is a server momentum, which is firstly proposed in FL by [Hsu et al., 2019](https://arxiv.org/abs/1909.06335), coined as `FedAvgM`.
This concept has also been adopted into other FL researches, e.g., [Dinh et al., 2022 (`pFedMe`)](https://arxiv.org/abs/2006.08848).
Since vanilla aggregation mechnism is the special case of the momentum verison (i.e., $\eta=1$), I intentionally implemented in that way.
Please correct me or PR, if I made an wrong statement or incorrect implementation.

BTW, I think I should explictly add `fedavgm` option to the choice of `algorithm` argument that forces the momentum constant (i.e., $\eta$) to be positive.
Thank you!



Best,
Adam

**Comment by bokun-wang** [comment]
Thanks for the clarification. 

[This paper](https://arXiv.org/abs/2201.11066)  also looks relevant, which suggests specific values for the server-side step size eta.
