### ISSUE TITLE
AttributeError: 'FedavgServer' object has no attribute 'lr_scheduler'

### ISSUE THREAD

**Issue by Jinfeng-Xu** [vaseline555/Federated-Learning-in-PyTorch#12]
Fantastic work!
I'm a freshman in the FL field.
When I use your project, it raises an error about 'AttributeError: 'FedavgServer' object has no attribute 'lr_scheduler''
Hoping to get your help!
Many thanks.

Kindest regards,
Jinfeng

**Comment by vaseline555** [comment]
Dear @Jinfeng-Xu ,
Thank you for your kind words!

Oops, I forgot to change that part when deubgging.
It is fixed in [this commit](https://github.com/vaseline555/Federated-Learning-in-PyTorch/commit/b8f9d30bfc9ca74dc18678bbab1eeacb24c90e46).
Please pull the latest version of this repo and try again.
And please let me know if there still exists a problem!

Thank you.
고마워요~

Best,
Adam

**Comment by Jinfeng-Xu** [comment]
Many Thanks!
But still, some bugs need to be fixed.
<img width="1156" alt="image" src="https://github.com/vaseline555/Federated-Learning-in-PyTorch/assets/73060940/c5ce78c7-cbf0-4253-992b-cc54c2dc4173">

server.update() may raise an error for unexpected type

**Comment by vaseline555** [comment]
Thank you for your report, @Jinfeng-Xu !
Could you please provide me corresponding command that causing such an error?

I presume that the error caused when you used `BCELoss`.
If in that case (plus if the dataset you want to use has at most 2 classes), however, you should change it into `BCEWithLogitsLoss` since any models provided in this repo do not have `torch.nn.Sigmoid()` activation in the final layer of the model (i.e., last layer of the model's `classifier` submodule).

FYI, it is an _intended_ behavior even if users entered metrics requiring probability ouputs (e.g., AUROC), because it is implicitly transformed in `MetricManager` instance.

Hope it helps.
Thank you!


Best,
Adam

**Comment by Jinfeng-Xu** [comment]
Thank you for your guidance, @vaseline555 !

Your guess is right, it works with BCEWithLogitsLoss.
Thanks for your help!

Sincerely,
Jinfeng

**Comment by vaseline555** [comment]
Sounds great!
Hope you have a nice Friday. 😄 
(불금 in Korean)

Best,
Adam
